default_platform(:android)

platform :android do
  lane :bump_version_code do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    s[re, 1] = (number_of_commits).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  lane :set_version do |opts|
    path = '../app/build.gradle'
        # versionName "1.0"
    re = /versionName\s+"(.+)"/

    s = File.read(path)
    s[re, 1] = opts[:tag]

    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  desc "Upload android to hockey app"
  lane :internal do |options|
    bump_version_code
    set_version(tag: options[:tag])
    gradle(task: "clean assembleRelease")
    changelog = options[:changelog].gsub('\r\n', "\n").gsub('\n', "\n").gsub('\r', "\n")
    hockey(
      api_token: "PHARAH_HOCKEY_APP_API",
      ipa: "./app/build/outputs/apk/release/app-release.apk",
      notify: "0",
      public_identifier: "PHARAH_HOCKEY_APP_ID",
      notes: changelog
    )
    url = lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK]
    ENV["SLACK_URL"] = "PHARAH_SLACK_URL"
    slack(message: "Released android app to HockeyApp", payload: {
        'url' => url,
    })
  end

  desc "Upload to TestFlight"
  lane :beta do |options|
    bump_version_code
    set_version(tag: options[:tag])
    gradle(task: "clean bundleRelease")
    changelog = options[:changelog].gsub('\r\n', "\n").gsub('\n', "\n").gsub('\r', "\n")
    upload_to_play_store
    ENV["SLACK_URL"] = "PHARAH_SLACK_URL"
    slack(message: "Released android app to PlayStore")
  end
end

