platform :ios, '9.0'

def react_pods
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end

target 'mercy' do
  react_pods

  pod 'Fabric', '~> 1.10.1'
  pod 'Crashlytics', '~> 3.13.1'

  firebase_version = '~> 6.2.0'

  pod 'Firebase/Core', firebase_version
  pod 'Firebase/Auth', firebase_version
  pod 'Firebase/Firestore', firebase_version
  pod 'Firebase/Functions', firebase_version
  pod 'Firebase/Messaging', firebase_version
  pod 'Firebase/RemoteConfig', firebase_version
  pod 'Firebase/Storage', firebase_version
  pod 'Firebase/Performance', firebase_version
  pod 'Firebase/Database', firebase_version

  pod 'IQKeyboardManager'

  pod 'FBSDKCoreKit', '~> 5.0'
  pod 'FBSDKLoginKit', '~> 5.0'
  pod 'FBSDKShareKit', '~> 5.0'
  pod 'GoogleSignIn', '~> 4.4.0'

  use_native_modules!
end


