platform :ios, '9.0'

def shared_pods
  pod 'React', path: '../node_modules/react-native', subspecs: [
      'Core',
      'CxxBridge', # Include this for RN >= 0.47
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
      'RCTText',
      'RCTImage',
      'RCTNetwork',
      'RCTWebSocket', # Needed for debugging
      'RCTAnimation', # Needed for FlatList and animations running on native UI thread
      'RCTActionSheet',
      'RCTCameraRoll',
      'RCTVibration',
      'RCTWebSocket',
      'RCTLinkingIOS',
      'RCTSettings'
  ]
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

end

target 'mercyTests' do
  shared_pods
end

target 'mercy' do
  shared_pods
  pod 'IQKeyboardManager'

  # Crashlytics
  pod 'Fabric', '~> 1.10.1'
  pod 'Crashlytics', '~> 3.13.1'

  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/Auth', '~> 6.2.0'
  pod 'Firebase/Firestore', '~> 6.2.0'
  pod 'Firebase/Functions', '~> 6.2.0'
  pod 'Firebase/Messaging', '~> 6.2.0'
  pod 'Firebase/RemoteConfig', '~> 6.2.0'
  pod 'Firebase/Storage', '~> 6.2.0'
  pod 'Firebase/Performance', '~> 6.2.0'

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'GoogleSignIn'
  pod 'SVProgressHUD'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios/RNFirebase.podspec'

  pod 'RNProgressHud', :path => '../node_modules/react-native-progress-display/ios/RNProgressHud.podspec'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

end


