default_platform(:ios)

platform :ios do
  desc "Upload to hockey app"
  lane :internal do |options|
    match(type: "development")
    increment_build_number(build_number: number_of_commits)
    increment_version_number(version_number: options[:tag])
    build_app(
        scheme: "mercy",
        export_options: {
          method: "development",
          provisioningProfiles: {
            "com.mercy" => "match Development com.mercy"
          }
        },
        silent: true
    )
    changelog = options[:changelog].gsub('\r\n', "\n").gsub('\n', "\n").gsub('\r', "\n")
    hockey(
      api_token: "PHARAH_HOCKEY_APP_API",
      ipa: "./mercy.ipa",
      dsym: "./mercy.app.dSYM.zip",
      notify: "0",
      public_identifier: "PHARAH_HOCKEY_APP_ID",
      notes: changelog,
      bypass_cdn: true
    )
    url = lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK]
    ENV["SLACK_URL"] = "PHARAH_SLACK_URL"
    slack(message: "Released iOS app to HockeyApp", payload: {
        'url' => url,
    })
  end

  desc "Upload to TestFlight"
  lane :beta do |options|
    match(type: "appstore")
    increment_build_number(build_number: number_of_commits)
    increment_version_number(version_number: options[:tag])
    build_app(scheme: "mercy", silent: true)
    changelog = options[:changelog].gsub('\r\n', "\n").gsub('\n', "\n").gsub('\r', "\n")
    upload_to_testflight(changelog: changelog)
    ENV["SLACK_URL"] = "PHARAH_SLACK_URL"
    slack(message: "Released iOS app to TestFlight")
  end
end
